# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbour', '0002_remove_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(default='choma', max_length=500),
            preserve_default=False,
        ),
    ]
