# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbour', '0003_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='l', max_length=150),
            preserve_default=False,
        ),
    ]
