# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myneighbour', '0004_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
